import React, {useState} from 'react';
import CommentList from '../components/CommentList.js';
import CommentForm from '../components/CommentForm.js'

const CommentBox = () => {

// setting up example of using state here - here we are hard-coding our state into this top level file which we won't always do!
// this is the first step of setting ourselves up to pass data from the top to bottom level of our hierarchy
    const [comments, setComments] = useState([
        {
            id: 1,
            author: "Rick Henry",
            text: "React is such a great framework!"
        },
        {
            id: 2,
            author: "Valerie Gibson",
            text: "I'm dreaming in React..."
        }
    ]);

    const saveNewComment = (newComment) => {
        // here we are grabbing the data generated by our form in the level below in our hierarchy - this'll work similarly to how we saw before, but we're going to shorthand it a little bit
        const commentsCopy = [...comments, newComment];
        setComments(commentsCopy);
    };
    
    return (

        <>
            <h1>Comments</h1>
            {/* here is where we pass our data through as props to the CommentList so that it can render it, using the key comments */}
            {/* so the green word "comments" is us naming our prop and then we've set it equal to the comments array we hard-coded above - SO THIS IS THE PROPS, THIS IS US SETTING THEM UP */}
            {/* inside of CommentList we set up the component with the parameters which will pull the data points we want, */}
            {/* but in here is where we actually pass the data down. So the initial set-up and passing to the next level is done all in this file */}
            <CommentList comments={comments} />
            <h2>Add a Comment</h2>
            {/* here where we render our form, we pass our saveNewComment function from above, which passes this function down to the form as a prop - the form can then use this */}
            <CommentForm onCommentSubmit={saveNewComment} />
        </>

    );

}

export default CommentBox;