PRAGMA FOREIGN_KEYS = ON;

DROP TABLE users;
DROP TABLE locations;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR
);

CREATE TABLE locations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category VARCHAR,
  name VARCHAR
);
